apiVersion: v1
kind: Service
metadata:
    name: "akscna-29ca"
    labels:
        app: "akscna-29ca"
spec:
    type: LoadBalancer
    ports:
    - port: 8464
      targetPort: 8464
      protocol: TCP
      name: http
    selector:
        app: "akscna-29ca"